#!/bin/bash
BASE_VERSION='v1470'
echo Make sure dockerfile has ${BASE_VERSION} for base image
export githash=`git rev-parse --short HEAD`
docker build --tag opentaproject/openta-wolfram:${VERSION} .
docker push opentaproject/openta-wolfram:${VERSION}
docker tag opentaproject/openta-wolfram:${VERSION} opentaproject/openta-wolfram:${githash}
docker push opentaproject/openta-wolfram:${VERSION}

